# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  digitecpricewatcher:
    image: digitecpricewatcher
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5214:5214
    volumes:
      - ./db:/db
